function error(client){
    throw "caught error";
}

module.exports.error = error;